# Generated by Django 5.0.4 on 2024-05-02 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='cover_image',
            field=models.URLField(null=True),
        ),
        migrations.AlterField(
            model_name='artist',
            name='image',
            field=models.URLField(null=True),
        ),
        migrations.AlterField(
            model_name='song',
            name='cover_image',
            field=models.URLField(null=True),
        ),
    ]
