# Generated by Django 5.0.4 on 2024-05-12 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0002_alter_album_cover_image_alter_artist_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='listened',
            field=models.PositiveBigIntegerField(default=0),
        ),
    ]
