# Generated by Django 5.0.4 on 2024-05-12 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0003_song_listened'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='song',
            options={'ordering': ['id']},
        ),
        migrations.AddIndex(
            model_name='song',
            index=models.Index(fields=['id'], name='music_song_id_82e124_idx'),
        ),
    ]
